POST http://localhost:5001/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZjNmZiZTg5YjQ1NDA2NWZjZjlhMiIsImVtYWlsIjoib2RhaUBleGFtcGxlLmNvbSIsIm5hbWUiOiJPZGFpIiwiaWF0IjoxNzQ1NDkyMjU5LCJleHAiOjE3NDU0OTU4NTl9.IxqBkfNUFsAjLyDvQGQqKCToPvqL16J1heTPdGFwSMQ


{
  "name": "Gucci cap",
  "price": 415.99,
  "description": "A stylish Gucci cap that can get you arrested in Sweden.",
  "stock": 20,
  "image": "https://www.gucci.com/se/en_gb/pr/men/accessories-for-men/hats-and-gloves-for-men/baseball-hats-for-men/original-gg-canvas-baseball-hat-with-web-p-200035KQWBG9791",
  "category": "clothing"
}
###

GET http://localhost:5001/api/products
###

DELETE  http://localhost:5001/api/products/13
###

PUT  http://localhost:5001/api/products/23
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWZjNmZiZTg5YjQ1NDA2NWZjZjlhMiIsImVtYWlsIjoib2RhaUBleGFtcGxlLmNvbSIsIm5hbWUiOiJPZGFpIiwiaWF0IjoxNzQ1NDkyMjU5LCJleHAiOjE3NDU0OTU4NTl9.IxqBkfNUFsAjLyDvQGQqKCToPvqL16J1heTPdGFwSMQ

{
  "price": 420.69
}
###
GET http://localhost:5001/api/users/login


###
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
  "name": "Odai",
  "email": "odai@example.com",
  "password": "password123"
}
###
POST http://localhost:5001/api/users/login
Content-Type: application/json

{
  "email": "odai@example.com",
  "password": "password123"
}